# Generated by Django 5.2.4 on 2025-07-04 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_link',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.group'),
        ),
    ]
