# Generated by Django 5.2.4 on 2025-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_event_image_link_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
